project:
  type: website
  output-dir: _site

website:
  title: "ISSS626"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 4"
            href: Hands-on_Ex04/Hand-on_Ex04
          - text: "Hands-on Exercise 3"
            href: Hands-on_Ex03/Hand-on_Ex03
          - text: "Hands-on Exercise 2"
            href: Hands-on_Ex02/Hand-on_Ex02
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex01/Hand-on_Ex01.qmd
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 4"
            href: In-Class_Ex04/in-class_ex4 
          - text: "In-class Exercise 3b"
            href: In-Class_Ex03b/in-class_Ex03b        
          - text: "In-class Exercise 3a"
            href: In-Class_Ex03/in-class_Ex03a
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/tanchinkhoon/ 
        aria-label: Linkedin
      - icon: github
        href: https://github.com/tanchinkhoon/ISSS626_Hands-on_Ex
        aria-label: Github

format:
  html:
    # --- Outline / TOC defaults (apply to all pages) ---
    toc: true                # show outline
    toc-title: "On this page"
    toc-location: right      # left | right
    toc-depth: 3             # include ### headings and above
    number-sections: false   # 1, 1.1, 1.2 numbering
    page-navigation: true    # Previous / Next links at bottom
    smooth-scroll: true      # nice scrolling when clicking TOC
    css: styles.css
    

