project:
  type: website
  output-dir: _site

website:
  title: "ISSS626"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex01/Hand-on_Ex01.qmd
          - text: "Hands-on Exercise 2a"
            href: Hands-on_Ex02/Hand-on_Ex02_a.qmd
          - text: "Hands-on Exercise 2b"
            href: Hands-on_Ex02/Hand-on_Ex02_b.qmd
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    css: styles.css
    

