project:
  type: website
  output-dir: _site

website:
  title: "ISSS626"
  navbar:
    left:
      - text: "Hand-on Exercise"
        menu:
          - text: "Hand-on Exercise 1"
            href: hands-on_ex01.qmd
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    css: styles.css
    

