---
title: "In-class Ex07: Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method"
author: "TAN Chin Khoon"
date: "18 October 2025"
date-modified: "last-modified"
number-sections: true
---

## Getting Started

```{r}

pacman::p_load(olsrr, ggstatsplot, ggpubr, 
               sf, spdep, GWmodel, tmap,
               tidyverse, gtsummary, performance,
               see, sfdep)

```



```{r}



```


```{r}



```




```{r}



```




```{r}



```



```{r}



```




```{r}



```




```{r}



```



```{r}



```




```{r}



```





```{r}



```





```{r}



```






```{r}



```





```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```





```{r}



```




```{r}



```



```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```



```{r}



```



```{r}



```



```{r}



```




```{r}



```




```{r}



```




```{r}



```





```{r}



```





```{r}



```





```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```




```{r}



```





```{r}



```




```{r}



```






```{r}



```




```{r}



```




```{r}



```




```{r}



```





```{r}



```






```{r}



```




```{r}



```




















































