---
title: "Hands-on_Ex02(a)"
author: "TAN Chin Khoon"
date: "5 September 2025"
---

# 5. 1st Order Spatial Point Patterns Analysis Methods

```{r}
pacman::p_load(                       # use pacman to auto-install (if needed) and load packages
  sf,                                 # 'sf' handles vector geospatial data (points/lines/polygons) in R
  spatstat,                           # 'spatstat' provides tools for spatial point pattern analysis (G/F/K/L, CSR tests, KDE)
  tmap,                               # 'tmap' creates cartographic-quality static/interactive maps
  tidyverse                           # 'tidyverse' offers consistent, beginner-friendly data wrangling/plotting helpers
)


```


```{r}
set.seed(1234)                                             # fix the random seed so plots are reproducible for students
G_CK <- Gest(childcare_ck_ppp, correction = "border")      # estimate nearest-neighbour CDF G(r) with border edge correction
plot(G_CK, xlim = c(0, 500))                               # plot G(r) up to 500 m; dashed line shows CSR (Poisson) reference


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```



```{r}


```


