---
title: "Hands-on_Ex05"
author: "TAN Chin Khoon"
date: "19 September 2025"
date-modified: "last-modified"
---

## 

```{r}
# Load required packages exactly as in the professor's notes -------------------

# pacman::p_load() creates a package list, installs any missing packages,
# and then loads them into the session.
pacman::p_load(sf, spdep, tmap, tidyverse)


```


```{r}
# Read the Hunan county-level shapefile as an sf object -----------------------

# st_read() reads vector geospatial data. Here we pass:
# - dsn: the directory containing the shapefile set
# - layer: the base name of the shapefile (without .shp)
hunan <- st_read(dsn = "data/geospatial",
                 layer = "Hunan")


```


```{r}

# Read attribute data (development indicators) from CSV -----------------------

# read_csv() reads a comma-separated file into a tibble (tidyverse data frame).
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")

```


```{r}



```


```{r}



```



```{r}



```


```{r}



```




```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```


```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```


```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```


```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```




```{r}



```


```{r}



```



```{r}



```



```{r}



```



```{r}



```


```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```




```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```




```{r}



```



```{r}



```



```{r}



```


























